name: Hello World

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one line script
        run: echo "Hello, World!"

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display files
        run: ls -la
